package org.wolf.crud;

import java.util.ArrayList;

import org.wolf.baseclasses.MedicalRecord;

public final class MedicalRecordCRUD {

	//Return All the medical records
	public static ArrayList<MedicalRecord> viewMedicalRecords(){
		return null;
	}
	
	//Return medical Record for a  given  recordId
	public static MedicalRecord viewMedicalRecords(Integer recordId){
		return null;
	}
	
	//Returns all the medical Records for a given PatientId
	public static ArrayList<MedicalRecord> getMedicalRecordsForPatient(Integer patientId){
		return null;
	}
	
	//Returns all the medical Records for a given responsible doctor Id
	public static ArrayList<MedicalRecord> getMedicalRecordsForDoctor(Integer doctor_id){
		return null;
		
	}
	
	//Insert a medical record for the given data
	//Return latest autogenerated id
	public static Integer insertMedicalRecord(Integer patient_id, String start_date,String end_date, String diagnosis, String prescription, String responsible_doctor){
		return null;
	}
	
	//Updates a medical record with the given data
	//Return true if successful else false
	public static Boolean updateMedicalRecord(Integer recordId, Integer patient_id, String start_date,String end_date, String diagnosis, String prescription, String responsible_doctor){
		return null;
	}
	
	//Deletes a medical record with the given recordId
	//Return true if successful else false
	public static Boolean deleteMedicalRecord(Integer record_id){
		return null;
	}

	public static Boolean updateMedicalRecordEndTime(Integer recordId) {
		// Update the end time to the current time stamp through SQL
		return null;
	}
}
